# Generated by Django 4.1 on 2023-01-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=12)),
                ('author', models.CharField(max_length=16)),
                ('created', models.DateField(auto_now_add=True)),
                ('text', models.TextField(max_length=500)),
                ('specification', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('cost', models.TextField(max_length=20)),
                ('amount', models.TextField(max_length=10)),
                ('slug', models.SlugField(max_length=200)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eshop.group')),
            ],
        ),
    ]
